### ISSUE TITLE
Track Epoch Start Time in the ClusterHistoryAccount

### ISSUE THREAD

**Issue by ebatsell** [jito-foundation/stakenet#18]
**Is your feature request related to a problem? Please describe.**
In order to better track APY of validators and stake pools on chain, we need to know the real world time that epochs started. The ClusterHistory account is the logical place to store this network-level field. 

**Describe the solution you'd like**
Use the epoch_start_ timestamp from the [Clock sysvar](https://docs.rs/solana-program/latest/solana_program/clock/struct.Clock.html) to read this field on chain for the current epoch and store it in the ClusterHistoryEntry for this epoch. This can be done in the `copy_cluster_info` instruction. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by butonium** [comment]
jm :coffee:, could I be assigned to this one? 
Additionally, do you have any hints for resolving the `test_copy_cluster_info` failure related to memory allocation?

**Comment by ebatsell** [comment]
@butonium yes! we're currently working on a fix for that, expect it to be resolved sometime next week. 
In the meantime, if you get to this before the fix is in, you can comment out the parts of the copy_cluster_info instruction and test related to the slot_history account and total_blocks. Then we can merge the fix into your PR and test everything properly
