### ISSUE TITLE
Feature: Build a StakeNet API that returns stakenet information in JSON format

### ISSUE THREAD

**Issue by buffalu** [jito-foundation/stakenet#8]
**Is your feature request related to a problem? Please describe.**
If users want to explore StakeNet data, they need to use solana libraries and anchor. There should be an API implementation that anyone can host that acts as a proxy, cache, and translation layer which allows easily querying of the ValidatorHistoryAccount in a JSON format.

This API can be useful for any website that wants to show historical information on validator performance!

**Describe the solution you'd like**
A rust, [axum](https://docs.rs/axum/latest/axum/)-based API in this repository that allows one to query StakeNet data over a variety of endpoints to get information on validator performance.

The server arguments should include the bind IP and port, an RPC URL, the stakenet program IDs (validator history for now), and others. It should spin up an HTTP server and host a variety of endpoints that allow querying the performance of validators at given points in time.

Some of these endpoints can look like the following (I am not an API engineer, please take this with a grain of salt):
- `GET /api/v1/validator_history/{vote_account}`
- `GET /api/v1/validator_history/{vote_account}?epoch={epoch}`

**Comment by dhruvsol** [comment]
Hey, 
Can I  take this?  @buffalu

**Comment by buffalu** [comment]
> Hey, Can I take this? @buffalu

yes @dhruvsol! feel free to ping us in discord if you need help.

here's a good start for an axum server we previously built: 
https://github.com/jito-foundation/distributor/blob/97e134a5f3b3da28130648d93da34100726e6dc9/api/src/main.rs#L51
